### PR TITLE
Not only 'ansible-pull' command has -e switch

### PR DESCRIPTION
**Pull request by 7aitsev**
Also some editing work was done: missed comma, ip->IP, ssh->SHH, line wrapping

### CODE REVIEW

**Comment by leucos** [comment]
Thanks a lot !

**Comment by 7aitsev** [comment]
Hello!

I mixed up `ansible-playbook` with `ansible-pull` :(

I've made a new commit, should I create a new pull request?

**Comment by leucos** [comment]
Oh ok, I went to fast too and overlooked this, sorry. !

**Comment by 7aitsev** [comment]
My apologies.

Thank you for the tutorial btw :)

**Pull request merged**
