### PR TITLE
Broken link update

### PR DESCRIPTION
**Pull request by mariuszmichalowski**
I was wondering whether you’d be interested in fixing the broken link in your post and replacing it with another resource on the same topic:)

### CODE REVIEW

**Comment by leucos** [comment]
Hello @mariuszmichalowski and thanks for the suggestion.
I'd rather put also the official link (https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html) here

**Comment by mariuszmichalowski** [comment]
> Hello @mariuszmichalowski and thanks for the suggestion. I'd rather put also the official link (https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html) here

Sure, let me know if my post on playbooks could be an additional resource:) @leucos

**Comment by leucos** [comment]
Sure , go ahead Marius

**Comment by mariuszmichalowski** [comment]
Let me know if that would be ok:) #127

**Pull request closed without merging**
