### PR TITLE
add gitbook functionality - rebase

### PR DESCRIPTION
**Pull request by tumregels**
Hi @leucos 

Here comes the rebase PR to master as suggested [here](https://github.com/leucos/ansible-tuto/pull/90#discussion_r65820094)

### CODE REVIEW

**Comment by leucos** [comment]
Awesome thanks !

**Comment by tumregels** [comment]
Great!

So now one last mile.
If you find time please read [this](https://github.com/GitbookIO/documentation/tree/master/github)
to connect the ansible-tuto repo to gitbook via  a webhook

Let me know if you experience any problems

**Comment by leucos** [comment]
Thanks @tumregels by I can not grant the permissions asked by gitbook (especially "Repository webhooks and services: Admin access". It is not clear on which repositories this will be granted (I understand: All of them). 
Since I belong to some organizations, I don't want them to be impacted by accepting this.

I you publish it under your account that's fine with me.

Thanks for all your efforts.

**Comment by tumregels** [comment]
I see @leucos 

No problem, in that case will try to do it from my account. 

Thanks for the great tutorial!

**Comment by tumregels** [comment]
@leucos finally hosted on [gitbook](
https://www.gitbook.com/book/tumregels/ansible-tutorial/details) from my account.

Would be great to post it on news.ycombinator.com to get some traffic and stars.

**Comment by leucos** [comment]
Thanks for this ! It seems you're missing from the contributors though :/

**Comment by tumregels** [comment]
Thanks for reminding! 
Will do it. Also there is a small problem with the gitbook. 
Fill try to fix it and send a pull request.

**Comment by tumregels** [comment]
@leucos as gitbook.com has become more of a private thing, I suggest you to host your tutorial on [github pages](https://pages.github.com/). You can check it hosted [here](https://tumregels.github.io/ansible-tuto/)

To do it on your end you need just 
```
    $ git clone https://github.com/leucos/ansible-tuto.git
    $ cd ansible-tuto
    $ npm install
    $ npm build
    $ npm publish
```

The only minor thing to change on your end is to change [this line](https://github.com/leucos/ansible-tuto/blob/master/book.json#L9) with [this one](https://github.com/tumregels/ansible-tuto/blob/master/book.json#L10)

**Pull request merged**
